// <auto-generated />

using System;
using System.Data.Entity.Migrations.Infrastructure;

namespace NLog.Mvc4.Web.Migrations
{
	public sealed partial class Initialisation : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203301819540_Initialisation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soxfPq4vxF5fTj9Ljssio/9d5ef6eyOw8BDIf2W6oo1NCqL1+c73KubPPPqJu6LP62m9F7X6v/Dr4gD56WVervG6vX+Xn+u7Z7KP0bvje3e6L9jXvHXRPvy3be3sfpS/WZZlNSvrgPCub/KN09emj121V55/ny7zO2nz2MmvbvF7i3ZzRVzI8Wn16O0o8vLuzB0rczZbLqs1amtse4h0039C0vW6zxcpg+5QwwYcRhDdDep5f5qWB8rqtieM+Sp8V7/LZ83x50c4tmC+yd+aT+x+lXy0LYk96pa3XX6PT6uIir9+zV6LUh/b7Oq8vv+F+5e/N3X6RN012kb9nv/Tr+4338V0nPn2hIulus4J41psDQgMf5+/ajnzJK6/z1jX+KHXQRdzHVjijaNgOnR65K4rEKJy7Axrn8RfZakW4eRpIP0lfi/o52X79/spmITDuTpuIzrHY2p5IyGnSOt9S14Tps6JuWhK5bJJhEk5mi16z25HXdOao3FVrjuimLX6X9kYJu4novO0I94zGsiD1xMPSQVH/QwpWX349zcqsjqjIk6pcL5ZDanbT257m8oF4H98eluouH45+9B4wVBUFQPSz20MxisWHYj67PRSrJ3ww9sM+nMd3O7PbZR5PIWjLjjnsMuImMe42sb1bce6I7WMVoZu9iZ5MSZOPUiLQZTGDPL2+btp8MUaD8etfVJ6UBY3XNfgiWxbnedO+qd7mS9bZB1/fNbEGuWlm5f9b/ZMCw7/RE3lPA9nzK2YEFz7ie0MK/IrlZVZP51nd9SLeF2bgNkSBsrF+T7ChV3AbsF/D6BuwW4vs3Z1v1JD3DdKAsemy7CaDLgJI8z+paASCKTsBX9PS91XB47t++PH4ad4UFw4EgpFlPoUv7ICaNmfL88pQm8blY2Sa9CajzYiVs+O6Lc6zaUtfT2l+2A37yaxcU5PTxSSfnS2/XLerdXvcNPliUgaezeO7m/tndybE+fGXK/zl6b6vPwRCs4A0frl8si7KmcX7WYR/BkCAU1RZEFbkhhK4i2sL6UW1vCUgJd/TfJUvoWre5ItVScCaL5evs8t8GLebaRhS7PHTIruos4VPQfnEyC7pqtLrgjrw33D90Z/ErhT7Hv0/AQAA//8wzJN/cA8AAA=="; }
        }
    }
}
