// <auto-generated />
namespace NLog.Mvc.Tests.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initialisation : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204041407150_Initialisation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soxfPq4vxF5fTj9Ljssio/9d5ef6eyOw8BDIf2W6oo1NCqL1+c73KubPPPqJu6LP62m9F7X6v/Dr4gD56WVervG6vX+Xn+u7Z7KP0bvje3e6L9jXvHXRPvy3be3sfpS/WZZlNSvrgPCub/KN09emj121V55/ny7zO2nz2MmvbvF7i3ZzRVzI8Wn16O0o8vLuzB0rczZbLqs1amtse4h0039C0vW6zxcpg+5QwwYcRhDdDep5f5qWB8rqtieM+Sp8V7/LZ83x50c4tmC+yd+aT+x+lXy0LYk96pa3XX6PT6uIir9+zV6LUh/b7Rd402UX+nh3Trx/a8ek7SBZNLDr+RruXvzf3/uUKnMps9UPu2Y77Z4Pyt0GAhGT69k1NOutnuevHd53u6ms0Uq1tVpDC8ASAsMDH+bu2o9zkldd56xp/lDroomvHVjNG0bAdOiV+V7S40fZ3B9T94y+y1Ypw89S/fpK+Ft1/sv36/TX9QmDcnTYRhW+xtT2RhiV26XxLXROmz4q6aUnfZZMMc3YyW/Sa3Y68pjNH5a5NcUQ3bfG7tDcW0E1E521HuGc0lgXZBh6WDor6H7Ju+vLraVZmdcQ+nVTlerEcsnGb3vbMhg/E+/j2sNRw+HD0o/eAoXYgAKKf3R6K1S0+GPvh7eF0lLQPrfPV7WF6qteH5318e1h9ZRpF8WuM3NeSPkz/8z60x3c7/N0VH08lastQEvV7J4qbFFm3ie3dKrSO4nqsSuRmZ7anVaTJRymR6bKYQaO8vm7afDFGg/HrX1SelAWN1zX4IlsW53nTvqne5kt2VQ6+vmds/cGmmZX/b3WPCwz/Rkf4Pd2knls7I7gIUd4bUuDWLi+zejrP6q4T+74wA681CpR91PcE23GNDNytRfbuznsDizqagyBv40H1nMcPgjbkEH4Q0L6T9x7g3s9x6zsgIWYR3029tA0OnKgb4vZJRQMQRNnp+5qeXV/xPb7rx/qPn+ZNceFAIPJf5lNMiwNq2pwtzytDbxqXj5Fp0mPoNiPBzY7rtjjPpi19PaXZZq/7J7NyDTZYTPLZ2fLLdbtat8dNky8mZeDJPr67uX92X0OcH3/JjOVp+q8/BEKzgO75cvlkXZQzi/ezvgwOgQCnqGokrCjqIHAX1xbSi2p5S0BKvqf5Kl9Csb7JF6uSgDVfLl9nl/kwbjfTMKTY46dFdlFnC5+C8omRM9LMpdcFdeC/4fqjP4ldKdF09P8EAAD//5wNHJXdEgAA"; }
        }
    }
}
